[book]
authors = ["Promovolve Team"]
language = "en"
src = "src"
title = "Promovolve: Ad Auction Algorithms & Architecture"

[build]
build-dir = "book/en"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
